/**
 * Estimate KPI Definitions
 *
 * Metrics related to project estimates, line items, markup, and profitability.
 * These are calculated at the estimate level before becoming project financials.
 *
 * AUDIT NOTES (2026-01-23):
 * - Added labor cushion and advanced profit metrics
 * - Estimates are stored in estimates table, line items in estimate_line_items
 * - Labor hours only apply to labor_internal category line items
 */

import { KPIMeasure } from './types';

export const estimateKPIs: KPIMeasure[] = [
  // ==========================================================================
  // BASIC ESTIMATE METRICS
  // ==========================================================================
  {
    id: 'estimate_total_amount',
    name: 'Total Amount',
    source: 'database',
    field: 'estimates.total_amount',
    formula: 'SUM(estimate_line_items.total) for approved estimate',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'EstimatesList, EstimateForm, financial comparisons',
    notes: 'Total estimated amount including markup for client presentation.',
    aliases: ['estimate amount', 'total estimate', 'estimate value'],
    relatedTo: ['estimate_cost', 'estimate_gross_profit'],
  },
  {
    id: 'estimate_total_cost',
    name: 'Total Cost',
    source: 'database',
    field: 'estimates.total_cost',
    formula: 'SUM(estimate_line_items.total_cost) for approved estimate',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Margin analysis, EstimateForm, cost tracking',
    notes: 'For labor items, uses billing rate (not actual cost) to hide cushion. For materials, uses actual vendor cost.',
    aliases: ['estimate cost', 'total cost', 'estimated cost'],
    relatedTo: ['estimate_total_amount', 'estimate_gross_profit'],
  },
  {
    id: 'estimate_contingency_amount',
    name: 'Contingency Amount',
    source: 'database',
    field: 'estimates.contingency_amount',
    formula: 'User-defined or calculated buffer amount',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'EstimateForm, budget planning, contingency allocation',
    notes: 'Additional buffer for unknowns, typically 5-15% of total.',
    aliases: ['contingency', 'buffer amount', 'estimate contingency'],
  },
  {
    id: 'estimate_contingency_percent',
    name: 'Contingency Percent',
    source: 'database',
    field: 'estimates.contingency_percent',
    formula: '(contingency_amount / total_amount) × 100',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'Budget display, EstimateForm summary',
    aliases: ['contingency %', 'buffer percent'],
  },
  {
    id: 'estimate_default_markup_percent',
    name: 'Default Markup Percent',
    source: 'database',
    field: 'estimates.default_markup_percent',
    formula: 'User-defined default for line items (typically 10-30%)',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'LineItemTable auto-fill, EstimateForm',
    notes: 'Default markup applied to line items when created.',
    aliases: ['default markup', 'standard markup'],
  },
  {
    id: 'estimate_target_margin_percent',
    name: 'Target Margin Percent',
    source: 'database',
    field: 'estimates.target_margin_percent',
    formula: 'User-defined profitability goal (typically 15-25%)',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'EstimateForm, performance tracking, margin analysis',
    aliases: ['target margin', 'profit target'],
  },
  {
    id: 'estimate_is_auto_generated',
    name: 'Is Auto Generated',
    source: 'database',
    field: 'estimates.is_auto_generated',
    formula: 'Boolean flag - true when created from Quick Work Order',
    dataType: 'boolean',
    domain: 'estimate',
    whereUsed: 'WorkOrders table, estimate filtering, WorkOrders page',
    notes: 'Indicates placeholder estimate created automatically.',
    aliases: ['auto generated', 'quick estimate'],
  },

  // ==========================================================================
  // LINE ITEM METRICS
  // ==========================================================================
  {
    id: 'estimate_line_item_total',
    name: 'Line Item Total',
    source: 'database',
    field: 'estimate_line_items.total',
    formula: 'quantity × price_per_unit',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'LineItemTable calculations, EstimateForm',
    notes: 'Total amount for this line item including markup.',
    aliases: ['line total', 'item total'],
  },
  {
    id: 'estimate_line_item_total_cost',
    name: 'Line Item Total Cost',
    source: 'database',
    field: 'estimate_line_items.total_cost',
    formula: 'quantity × cost_per_unit',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Cost analysis, internal profitability tracking',
    aliases: ['line cost', 'item cost', 'actual cost'],
  },
  {
    id: 'estimate_line_item_markup_amount',
    name: 'Line Item Markup Amount',
    source: 'database',
    field: 'estimate_line_items.markup_amount',
    formula: 'total - total_cost',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Profitability by item, markup analysis',
    aliases: ['markup amount', 'profit amount'],
  },
  {
    id: 'estimate_line_item_markup_percent',
    name: 'Line Item Markup Percent',
    source: 'database',
    field: 'estimate_line_items.markup_percent',
    formula: '(markup_amount / total_cost) × 100',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'LineItemTable display, EstimateForm summary',
    aliases: ['markup %', 'profit margin %'],
  },

  // ==========================================================================
  // LABOR CUSHION & ADVANCED PROFIT METRICS
  // ==========================================================================
  {
    id: 'estimate_labor_hours',
    name: 'Labor Hours',
    source: 'database',
    field: 'estimate_line_items.labor_hours',
    formula: 'Hours for labor_internal line items only',
    dataType: 'number',
    domain: 'estimate',
    whereUsed: 'Labor planning, capacity analysis, EstimateSummaryCard',
    notes: 'Only populated for labor_internal category. Used for time tracking and resource planning.',
    aliases: ['labor hours', 'hours', 'estimated hours'],
    relatedTo: ['estimate_labor_cushion_amount', 'estimate_max_gross_profit_potential'],
  },
  {
    id: 'estimate_billing_rate_per_hour',
    name: 'Billing Rate Per Hour',
    source: 'database',
    field: 'estimate_line_items.billing_rate_per_hour',
    formula: 'Rate shown to client (e.g., $75/hr)',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Labor line items, client pricing, EstimateForm',
    notes: 'What the client is charged per hour. Used as cost_per_unit to hide actual labor cost.',
    aliases: ['billing rate', 'hourly rate', 'client rate'],
  },
  {
    id: 'estimate_actual_cost_rate_per_hour',
    name: 'Actual Cost Rate Per Hour',
    source: 'database',
    field: 'estimate_line_items.actual_cost_rate_per_hour',
    formula: 'True internal cost (e.g., $35/hr)',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Internal profitability tracking, labor cost analysis',
    notes: 'Hidden from client. Represents true cost to RCG for labor.',
    aliases: ['actual rate', 'internal rate', 'true cost rate'],
  },
  {
    id: 'estimate_labor_cushion_amount',
    name: 'Labor Cushion Amount',
    source: 'database',
    field: 'estimate_line_items.labor_cushion_amount',
    formula: '(billing_rate - actual_cost_rate) × labor_hours',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Estimate summary, profit opportunity tracking, EstimateSummaryCard',
    notes: 'Hidden profit opportunity built into labor billing. (billing_rate - actual_cost_rate) × hours.',
    aliases: ['labor cushion', 'labor profit', 'hidden profit', 'cushion amount'],
    relatedTo: ['estimate_total_labor_cushion', 'estimate_max_gross_profit_potential'],
  },
  {
    id: 'estimate_total_labor_cushion',
    name: 'Total Labor Cushion',
    source: 'frontend',
    field: 'calculateTotalLaborCushionAmount()',
    formula: 'SUM(labor_cushion_amount) for all labor items',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'EstimateSummaryCard, profit analysis',
    notes: 'Total hidden profit opportunity from all labor line items.',
    aliases: ['total cushion', 'labor opportunity', 'hidden profit total'],
  },
  {
    id: 'estimate_max_gross_profit_potential',
    name: 'Max Gross Profit Potential',
    source: 'frontend',
    field: 'trueProfitMargin',
    formula: 'Gross Profit + Total Labor Cushion',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'EstimateSummaryCard, portfolio analysis',
    notes: 'Maximum achievable profit if all labor cushion is captured.',
    aliases: ['max profit', 'true profit', 'profit potential'],
  },
  {
    id: 'estimate_max_potential_margin_percent',
    name: 'Max Potential Margin',
    source: 'frontend',
    field: 'trueProfitPercent',
    formula: '(Max Gross Profit / (Total Cost - Labor Cushion)) × 100',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'EstimateSummaryCard, margin analysis',
    notes: 'True margin based on actual costs, not billing costs. Shows what margin really is.',
    aliases: ['true margin', 'actual margin %', 'real margin percent'],
  },
  {
    id: 'estimate_true_actual_cost',
    name: 'True Actual Cost',
    source: 'frontend',
    field: 'trueActualCost',
    formula: 'Total Cost - Total Labor Cushion',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Internal margin calculations, cost analysis',
    notes: 'What the project actually costs internally (billing costs minus cushion).',
    aliases: ['true cost', 'actual internal cost', 'real cost'],
  },
  {
    id: 'estimate_gross_profit',
    name: 'Gross Profit',
    source: 'frontend',
    field: 'calculateEstimateGrossProfit()',
    formula: 'Total Amount - Total Cost',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'EstimatesList, EstimateSummaryCard, financial reports',
    notes: 'Standard visible markup profit only (excludes labor cushion).',
    aliases: ['profit', 'markup profit', 'gross margin amount'],
  },
  {
    id: 'estimate_gross_margin',
    name: 'Gross Margin',
    source: 'frontend',
    field: 'calculateEstimateGrossMargin()',
    formula: '(Gross Profit / Total Amount) × 100',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'Performance indicators, EstimatesList',
    notes: 'Margin shown to clients (excludes labor cushion).',
    aliases: ['margin %', 'profit margin', 'markup percent'],
  },
  {
    id: 'estimate_average_markup',
    name: 'Average Markup',
    source: 'frontend',
    field: 'calculateEstimateAverageMarkup()',
    formula: 'AVG(line_items.markup_percent)',
    dataType: 'percent',
    domain: 'estimate',
    whereUsed: 'EstimateForm summary, performance analysis',
    aliases: ['avg markup', 'average profit margin'],
  },
  {
    id: 'estimate_total_markup',
    name: 'Total Markup',
    source: 'frontend',
    field: 'calculateEstimateTotalMarkup()',
    formula: 'SUM(line_items.markup_amount)',
    dataType: 'currency',
    domain: 'estimate',
    whereUsed: 'Financial analysis, EstimateForm summary',
    aliases: ['total markup amount', 'total profit amount'],
  },
];

export default estimateKPIs;