/**
 * Project Financial KPI Definitions
 * 
 * Core project-level financial metrics and margin calculations.
 * These are the primary metrics for project profitability analysis.
 * 
 * AUDIT NOTES (2026-01-23):
 * - Standardized all view references to `reporting.project_financials`
 * - Clarified margin terminology (current vs actual vs projected)
 * - Added semantic aliases for AI matching
 * - Fixed source types (some were incorrectly marked as 'frontend')
 */

import { KPIMeasure } from './types';

export const projectFinancialKPIs: KPIMeasure[] = [
  // ==========================================================================
  // REVENUE METRICS
  // ==========================================================================
  {
    id: 'contracted_amount',
    name: 'Contracted Amount',
    source: 'database',
    field: 'projects.contracted_amount',
    formula: 'Base estimate amount + approved change order client amounts',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'ProjectDetailView, ProfitAnalysis, MarginDashboard',
    notes: 'Total contract value with client. Updated by triggers when estimates approved or change orders accepted.',
    aliases: ['contract value', 'contract amount', 'total contract', 'revenue'],
    relatedTo: ['total_invoiced', 'change_order_revenue'],
    preferWhen: 'User asks about expected/contracted revenue',
    avoidWhen: 'User asks about actual received revenue (use total_invoiced instead)'
  },
  {
    id: 'total_invoiced',
    name: 'Total Invoiced',
    source: 'view',
    field: 'reporting.project_financials.total_invoiced',
    formula: 'SUM(project_revenues.amount) for direct + SUM(revenue_splits.split_amount) for splits',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'ProfitAnalysis, BillingProgressTable, financial dashboards',
    notes: 'Actual revenue received. Handles split invoices correctly via the view.',
    aliases: ['invoiced', 'billed', 'actual revenue', 'received'],
    relatedTo: ['contracted_amount', 'revenue_variance'],
    preferWhen: 'User asks about actual/real revenue received',
  },
  {
    id: 'invoice_count',
    name: 'Invoice Count',
    source: 'view',
    field: 'reporting.project_financials.invoice_count',
    formula: 'COUNT(project_revenues) + COUNT(revenue_splits)',
    dataType: 'number',
    domain: 'project',
    whereUsed: 'Project summary, financial reports',
    notes: 'Total number of invoices/revenue entries for the project.',
  },
  {
    id: 'revenue_variance',
    name: 'Revenue Variance',
    source: 'view',
    field: 'reporting.project_financials.revenue_variance',
    formula: 'contracted_amount - total_invoiced',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'BillingProgressTable, variance analysis',
    notes: 'How much is left to bill. Positive = still owed, Negative = overbilled.',
    aliases: ['billing gap', 'remaining to bill', 'unbilled'],
  },

  // ==========================================================================
  // MARGIN METRICS - CRITICAL DISTINCTIONS
  // ==========================================================================
  {
    id: 'current_margin',
    name: 'Current Margin',
    source: 'database',
    field: 'projects.current_margin',
    formula: 'contracted_amount - total_expenses',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'MarginDashboard, ProjectProfitMargin, WorkOrders table',
    notes: 'UNREALIZED margin based on contract value minus expenses. Does NOT reflect actual invoiced revenue.',
    aliases: ['margin', 'expected margin'],
    relatedTo: ['actual_margin', 'projected_margin', 'original_margin'],
    preferWhen: 'User asks about expected/projected margin based on contract',
    avoidWhen: 'User asks about real/actual profit (use actual_margin)'
  },
  {
    id: 'actual_margin',
    name: 'Actual Margin',
    source: 'database',
    field: 'projects.actual_margin',
    formula: 'total_invoiced - total_expenses',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'ProfitAnalysis, MarginAnalysisTable',
    notes: 'REAL profit based on actual invoices received minus actual expenses. This is true profit.',
    aliases: ['real margin', 'real profit', 'actual profit', 'profit', 'true margin'],
    relatedTo: ['current_margin', 'total_invoiced', 'total_expenses'],
    preferWhen: 'User asks about actual/real/true profit or margin',
  },
  {
    id: 'projected_margin',
    name: 'Projected Margin',
    source: 'database',
    field: 'projects.projected_margin',
    formula: 'contracted_amount - adjusted_est_costs',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'WorkOrders table, margin forecasting',
    notes: 'Expected final margin based on current estimates (adjusted for accepted quotes).',
    aliases: ['expected margin', 'forecast margin'],
    relatedTo: ['current_margin', 'adjusted_est_costs'],
    preferWhen: 'User asks about expected/projected final margin',
  },
  {
    id: 'original_margin',
    name: 'Original Margin',
    source: 'database',
    field: 'projects.original_margin',
    formula: 'contracted_amount - original_est_costs',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Variance analysis, margin comparison',
    notes: 'Margin from original approved estimate. Immutable baseline for comparison.',
    aliases: ['baseline margin', 'initial margin'],
    relatedTo: ['projected_margin', 'original_est_costs'],
    preferWhen: 'User asks about original/baseline margin for comparison',
  },
  {
    id: 'margin_percentage',
    name: 'Margin Percentage',
    source: 'database',
    field: 'projects.margin_percentage',
    formula: '(current_margin / contracted_amount) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Dashboard cards, financial reports, project lists',
    notes: 'Current margin as percentage of contract value.',
    aliases: ['margin %', 'margin percent', 'profit margin'],
  },

  // ==========================================================================
  // COST METRICS
  // ==========================================================================
  {
    id: 'total_expenses',
    name: 'Total Expenses',
    source: 'view',
    field: 'reporting.project_financials.total_expenses',
    formula: 'SUM(expenses.amount) for direct + SUM(expense_splits.split_amount) for splits',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'All financial views, margin calculations',
    notes: 'All actual costs incurred. Handles split expenses correctly via the view.',
    aliases: ['costs', 'actual costs', 'expenses', 'spent'],
    relatedTo: ['adjusted_est_costs', 'original_est_costs', 'cost_variance'],
  },
  {
    id: 'original_est_costs',
    name: 'Original Estimated Costs',
    source: 'database',
    field: 'projects.original_est_costs',
    formula: 'Total cost from original approved estimate',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'WorkOrders table, variance analysis',
    notes: 'Immutable baseline cost estimate. Set when estimate first approved.',
    aliases: ['original costs', 'baseline costs', 'initial estimate'],
  },
  {
    id: 'adjusted_est_costs',
    name: 'Adjusted Estimated Costs',
    source: 'database',
    field: 'projects.adjusted_est_costs',
    formula: 'original_est_costs + accepted_quote_costs + change_order_costs',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'WorkOrders table, current budget tracking',
    notes: 'Current expected costs including all approved changes.',
    aliases: ['current estimate', 'revised costs', 'budget'],
  },
  {
    id: 'cost_variance',
    name: 'Cost Variance',
    source: 'view',
    field: 'reporting.project_financials.cost_variance',
    formula: 'total_expenses - adjusted_est_costs',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'CostAnalysisTable, variance reports',
    notes: 'Positive = over budget, Negative = under budget.',
    aliases: ['budget variance', 'over/under budget'],
    relatedTo: ['budget_utilization_percent'],
  },
  {
    id: 'cost_variance_percent',
    name: 'Cost Variance Percentage',
    source: 'view',
    field: 'reporting.project_financials.cost_variance_percent',
    formula: '(cost_variance / adjusted_est_costs) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Variance analysis dashboards',
    notes: 'Cost variance as percentage of budget.',
  },
  {
    id: 'budget_utilization_percent',
    name: 'Budget Utilization',
    source: 'view',
    field: 'reporting.project_financials.budget_utilization_percent',
    formula: '(total_expenses / adjusted_est_costs) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Progress tracking, dashboards',
    notes: 'Percentage of estimated budget consumed. Uses adjusted_est_costs (budget) as denominator, not contracted_amount (revenue).',
    aliases: ['budget used', 'spend rate'],
  },
  {
    id: 'remaining_budget',
    name: 'Remaining Budget',
    source: 'view',
    field: 'reporting.project_financials.remaining_budget',
    formula: 'adjusted_est_costs - total_expenses',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Budget tracking, project dashboards',
    notes: 'How much of the estimated budget is left to spend. Different from current_margin which uses contracted_amount (revenue).',
    aliases: ['budget remaining', 'available budget'],
  },

  // ==========================================================================
  // CONTINGENCY METRICS
  // ==========================================================================
  {
    id: 'contingency_amount',
    name: 'Contingency Amount',
    source: 'database',
    field: 'projects.contingency_amount',
    formula: 'User-defined buffer for unknowns (typically % of estimate)',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'ContingencyAllocation, budget tracking',
    notes: 'Total contingency allocated to project.',
    aliases: ['contingency', 'buffer', 'reserve'],
  },
  {
    id: 'contingency_used',
    name: 'Contingency Used',
    source: 'database',
    field: 'projects.contingency_used',
    formula: 'SUM(expenses marked as contingency) + change orders using contingency',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'ContingencyAllocation, financial dashboards',
    notes: 'How much contingency has been consumed.',
  },
  {
    id: 'contingency_remaining',
    name: 'Contingency Remaining',
    source: 'database',
    field: 'projects.contingency_remaining',
    formula: 'contingency_amount - contingency_used',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Budget planning, risk assessment',
    notes: 'Available contingency buffer.',
    aliases: ['available contingency'],
  },
  {
    id: 'contingency_percent',
    name: 'Contingency Percentage',
    source: 'database',
    field: 'projects.contingency_percent',
    formula: '(contingency_amount / contracted_amount) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Budget analysis',
  },

  // ==========================================================================
  // TARGET/THRESHOLD METRICS
  // ==========================================================================
  {
    id: 'target_margin',
    name: 'Target Margin',
    source: 'database',
    field: 'projects.target_margin',
    formula: 'User-defined goal amount',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'MarginDashboard, budget planning',
    notes: 'Desired margin goal for the project.',
  },
  {
    id: 'target_margin_percent',
    name: 'Target Margin Percentage',
    source: 'database',
    field: 'projects.target_margin_percent',
    formula: '(target_margin / contracted_amount) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Performance indicators',
  },
  {
    id: 'minimum_margin',
    name: 'Minimum Margin',
    source: 'database',
    field: 'projects.minimum_margin',
    formula: 'User-defined floor amount (alert threshold)',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Risk alerts, MarginDashboard',
    notes: 'Below this triggers warnings.',
  },
  {
    id: 'minimum_margin_percent',
    name: 'Minimum Margin Percentage',
    source: 'database',
    field: 'projects.minimum_margin_percent',
    formula: '(minimum_margin / contracted_amount) × 100',
    dataType: 'percent',
    domain: 'project',
    whereUsed: 'Warning thresholds',
  },

  // ==========================================================================
  // QUOTE AGGREGATES
  // ==========================================================================
  {
    id: 'total_accepted_quotes',
    name: 'Total Accepted Quotes',
    source: 'database',
    field: 'projects.total_accepted_quotes',
    formula: 'SUM(quotes.quote_amount WHERE status = accepted)',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Project financials, cost tracking',
    notes: 'Sum of all accepted vendor quotes.',
    // NOTE: This duplicates accepted_quotes_total in the view - prefer the projects field
    aliases: ['accepted quotes', 'vendor quotes total'],
  },

  // ==========================================================================
  // LABOR CUSHION METRICS (Project-Level Aggregates)
  // ==========================================================================
  {
    id: 'estimated_labor_cushion',
    name: 'Estimated Labor Cushion',
    source: 'view',
    field: 'reporting.project_financials.estimated_labor_cushion',
    formula: 'SUM(labor_cushion_amount) from approved estimates',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Project dashboards, portfolio analysis',
    notes: 'Hidden profit opportunity from billing labor at $75/hr vs $35/hr actual cost.',
    aliases: ['labor opportunity', 'labor profit', 'cushion'],
  },
  {
    id: 'estimated_max_profit_potential',
    name: 'Estimated Max Profit Potential',
    source: 'view',
    field: 'reporting.project_financials.estimated_max_profit_potential',
    formula: 'SUM(max_gross_profit_potential) from approved estimates',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'Project financial tracking',
    notes: 'Maximum achievable profit if all labor cushion is captured.',
    aliases: ['max profit', 'profit potential'],
  },
  {
    id: 'estimated_labor_hours',
    name: 'Estimated Labor Hours',
    source: 'view',
    field: 'reporting.project_financials.estimated_labor_hours',
    formula: 'SUM(labor_hours) from approved estimates',
    dataType: 'number',
    domain: 'project',
    whereUsed: 'Resource planning, scheduling',
    notes: 'Total internal labor hours across approved estimates.',
    aliases: ['labor hours', 'estimated hours'],
  },

  // ==========================================================================
  // PROJECT METADATA
  // ==========================================================================
  {
    id: 'project_status',
    name: 'Project Status',
    source: 'database',
    field: 'projects.status',
    formula: "ENUM: 'estimating' | 'quoted' | 'approved' | 'in_progress' | 'complete' | 'on_hold' | 'cancelled'",
    dataType: 'enum',
    domain: 'project',
    whereUsed: 'All project views, filtering',
    aliases: ['status'],
  },
  {
    id: 'project_type',
    name: 'Project Type',
    source: 'database',
    field: 'projects.project_type',
    formula: "ENUM: 'construction_project' | 'work_order'",
    dataType: 'enum',
    domain: 'project',
    whereUsed: 'Project creation, WorkOrders page',
    notes: 'Distinguishes full projects from work orders.',
  },
  {
    id: 'project_category',
    name: 'Project Category',
    source: 'database',
    field: 'projects.category',
    formula: "ENUM: 'construction' | 'system' | 'overhead'",
    dataType: 'enum',
    domain: 'project',
    whereUsed: 'All project queries, filtering',
    notes: 'CRITICAL: Filter by category=construction for most reports. System/overhead are internal.',
    aliases: ['category'],
  },
  {
    id: 'do_not_exceed',
    name: 'Do Not Exceed',
    source: 'database',
    field: 'projects.do_not_exceed',
    formula: 'Maximum billable amount (work orders)',
    dataType: 'currency',
    domain: 'project',
    whereUsed: 'WorkOrders table, QuickWorkOrderForm',
    notes: 'Budget cap for work orders.',
    aliases: ['DNE', 'budget cap', 'max budget'],
  },
];

export default projectFinancialKPIs;
