/**
 * View KPI Definitions
 *
 * KPIs for database views that aggregate or transform data.
 * Views have their own column names that may differ from source tables.
 *
 * @version 1.0.0
 * @lastUpdated 2026-01-29
 */

import { KPIMeasure } from './types';

export const viewKPIs: KPIMeasure[] = [
  // ==========================================================================
  // WEEKLY LABOR HOURS VIEW
  // ==========================================================================
  {
    id: 'weekly_labor_employee_name',
    name: 'Employee Name (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.employee_name',
    formula: 'Derived from payees.payee_name via time entry aggregation',
    dataType: 'text',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports',
    notes: 'Employee name aggregated from time entries for the week.',
    aliases: ['employee', 'worker', 'employee_name'],
  },
  {
    id: 'weekly_labor_employee_number',
    name: 'Employee Number (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.employee_number',
    formula: 'Derived from payees.employee_number',
    dataType: 'text',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports',
    aliases: ['employee #', 'emp number'],
  },
  {
    id: 'weekly_labor_week_start',
    name: 'Week Start (Sunday)',
    source: 'view',
    field: 'weekly_labor_hours.week_start_sunday',
    formula: 'DATE_TRUNC(week, expense_date) adjusted to Sunday start',
    dataType: 'date',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, date filtering',
    notes: 'First day of the week (Sunday) for the aggregated data.',
    aliases: ['week start', 'week starting', 'week_start_sunday'],
  },
  {
    id: 'weekly_labor_week_end',
    name: 'Week End (Saturday)',
    source: 'view',
    field: 'weekly_labor_hours.week_end_saturday',
    formula: 'week_start_sunday + 6 days',
    dataType: 'date',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports',
    notes: 'Last day of the week (Saturday).',
    aliases: ['week end', 'week ending', 'week_end_saturday'],
  },
  {
    id: 'weekly_labor_total_hours',
    name: 'Total Hours (Weekly Net)',
    source: 'view',
    field: 'weekly_labor_hours.total_hours',
    formula: 'SUM(expenses.hours) for the week',
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, payroll',
    notes: 'Total net billable hours for the week (after lunch deductions).',
    aliases: ['total hours', 'weekly hours', 'hours'],
  },
  {
    id: 'weekly_labor_gross_hours',
    name: 'Gross Hours (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.gross_hours',
    formula: 'SUM(calculated gross hours) for the week',
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, compliance',
    notes: 'Total gross shift hours for the week (before lunch deductions). VERIFY THIS COLUMN EXISTS IN VIEW.',
    aliases: ['gross hours', 'shift hours'],
  },
  {
    id: 'weekly_labor_total_cost',
    name: 'Total Cost (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.total_cost',
    formula: 'SUM(expenses.amount) for the week',
    dataType: 'currency',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, cost analysis',
    notes: 'Total labor cost for the week.',
    aliases: ['total cost', 'weekly cost', 'labor cost'],
  },
  {
    id: 'weekly_labor_hourly_rate',
    name: 'Hourly Rate (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.hourly_rate',
    formula: 'From payees.hourly_rate or calculated average',
    dataType: 'currency',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports',
    aliases: ['rate', 'hourly rate'],
  },
  {
    id: 'weekly_labor_entry_count',
    name: 'Entry Count (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.entry_count',
    formula: 'COUNT(expenses) for the week',
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports',
    notes: 'Number of time entries in the week.',
    aliases: ['entries', 'entry count'],
  },
  {
    id: 'weekly_labor_approved_entries',
    name: 'Approved Entries (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.approved_entries',
    formula: "COUNT(expenses WHERE approval_status='approved')",
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, approval tracking',
    aliases: ['approved', 'approved count'],
  },
  {
    id: 'weekly_labor_pending_entries',
    name: 'Pending Entries (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.pending_entries',
    formula: "COUNT(expenses WHERE approval_status='pending')",
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, approval tracking',
    aliases: ['pending', 'pending count'],
  },
  {
    id: 'weekly_labor_rejected_entries',
    name: 'Rejected Entries (Weekly)',
    source: 'view',
    field: 'weekly_labor_hours.rejected_entries',
    formula: "COUNT(expenses WHERE approval_status='rejected')",
    dataType: 'number',
    domain: 'time_entry',
    whereUsed: 'Weekly labor reports, approval tracking',
    aliases: ['rejected', 'rejected count'],
  },

  // ==========================================================================
  // TRAINING STATUS VIEW
  // ==========================================================================
  {
    id: 'training_employee_name',
    name: 'Employee Name (Training)',
    source: 'view',
    field: 'reporting.training_status.employee_name',
    formula: 'From payees.payee_name via training assignment',
    dataType: 'text',
    domain: 'training',
    whereUsed: 'Training reports',
    aliases: ['employee', 'trainee'],
  },
  {
    id: 'training_content_title',
    name: 'Content Title',
    source: 'view',
    field: 'reporting.training_status.content_title',
    formula: 'From training_content.title',
    dataType: 'text',
    domain: 'training',
    whereUsed: 'Training reports',
    aliases: ['title', 'training title', 'content'],
  },
  {
    id: 'training_content_type',
    name: 'Content Type',
    source: 'view',
    field: 'reporting.training_status.content_type',
    formula: "ENUM: 'video_link' | 'video_embed' | 'document' | 'presentation' | 'external_link'",
    dataType: 'enum',
    domain: 'training',
    whereUsed: 'Training reports',
    aliases: ['type', 'format'],
  },
  {
    id: 'training_status',
    name: 'Training Status',
    source: 'view',
    field: 'reporting.training_status.status',
    formula: "CALCULATED: 'completed' | 'overdue' | 'assigned' | 'pending'",
    dataType: 'enum',
    domain: 'training',
    whereUsed: 'Training reports, compliance tracking',
    aliases: ['status', 'completion status'],
  },
  {
    id: 'training_is_required',
    name: 'Is Required',
    source: 'view',
    field: 'reporting.training_status.is_required',
    formula: 'Boolean - whether training is mandatory',
    dataType: 'boolean',
    domain: 'training',
    whereUsed: 'Training reports, compliance',
    aliases: ['required', 'mandatory'],
  },
  {
    id: 'training_due_date',
    name: 'Due Date',
    source: 'view',
    field: 'reporting.training_status.due_date',
    formula: 'Date training must be completed by',
    dataType: 'date',
    domain: 'training',
    whereUsed: 'Training reports, deadline tracking',
    aliases: ['due', 'deadline'],
  },
  {
    id: 'training_days_remaining',
    name: 'Days Remaining',
    source: 'view',
    field: 'reporting.training_status.days_remaining',
    formula: 'due_date - CURRENT_DATE',
    dataType: 'number',
    domain: 'training',
    whereUsed: 'Training reports, deadline tracking',
    notes: 'Negative values indicate overdue.',
    aliases: ['remaining', 'days left'],
  },
  {
    id: 'training_assigned_at',
    name: 'Assigned At',
    source: 'view',
    field: 'reporting.training_status.assigned_at',
    formula: 'Timestamp when training was assigned',
    dataType: 'date',
    domain: 'training',
    whereUsed: 'Training reports',
    aliases: ['assigned', 'assignment date'],
  },
  {
    id: 'training_completed_at',
    name: 'Completed At',
    source: 'view',
    field: 'reporting.training_status.completed_at',
    formula: 'Timestamp when training was completed',
    dataType: 'date',
    domain: 'training',
    whereUsed: 'Training reports',
    aliases: ['completed', 'completion date'],
  },
];

export default viewKPIs;