import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";
import { format } from "date-fns";
import type {
  PaymentApplication,
  PaymentApplicationLineWithSOV,
} from "@/types/paymentApplication";

export interface ProjectInfo {
  projectId: string;
  projectName: string;
  projectNumber: string | null;
  clientName: string | null;
}

export interface PdfSaveResult {
  publicUrl: string;
  storagePath: string;
  fileName: string;
}

function formatCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 2,
  }).format(value);
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF GENERATION — returns Blob + filename (no side effects)
// ─────────────────────────────────────────────────────────────────────────────

function buildG702Doc(
  app: PaymentApplication,
  project: ProjectInfo
): { doc: jsPDF; fileName: string } {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Title
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("AIA DOCUMENT G702", pageWidth / 2, y, { align: "center" });
  y += 6;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("APPLICATION AND CERTIFICATE FOR PAYMENT", pageWidth / 2, y, {
    align: "center",
  });
  y += 10;

  // Header info
  doc.setFontSize(9);
  const col1 = margin;
  const col2 = pageWidth / 2 + 10;

  const addField = (label: string, value: string, x: number) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, x, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, x + 40, y);
  };

  addField("TO (Owner):", project.clientName || "—", col1);
  addField("APPLICATION NO:", String(app.application_number), col2);
  y += 6;
  addField("PROJECT:", project.projectName, col1);
  addField("PROJECT NO:", project.projectNumber || "—", col2);
  y += 6;
  addField("PERIOD TO:", new Date(app.period_to).toLocaleDateString(), col1);
  y += 10;

  // Separator
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // G702 calculation lines
  doc.setFontSize(10);
  const lines = [
    { num: 1, label: "ORIGINAL CONTRACT SUM", value: app.original_contract_sum },
    { num: 2, label: "Net change by Change Orders", value: app.net_change_orders },
    { num: 3, label: "CONTRACT SUM TO DATE (Line 1 + 2)", value: app.contract_sum_to_date },
    { num: 4, label: "TOTAL COMPLETED & STORED TO DATE", value: app.total_completed_to_date },
    { num: 5, label: "RETAINAGE", value: app.total_retainage },
    { num: 6, label: "TOTAL EARNED LESS RETAINAGE (Line 4 - 5)", value: app.total_earned_less_retainage },
    { num: 7, label: "LESS PREVIOUS CERTIFICATES FOR PAYMENT", value: app.total_previous_payments },
    { num: 8, label: "CURRENT PAYMENT DUE (Line 6 - 7)", value: app.current_payment_due },
    { num: 9, label: "BALANCE TO FINISH, INCLUDING RETAINAGE (Line 3 - 4)", value: app.balance_to_finish },
  ];

  const valueX = pageWidth - margin;

  lines.forEach(({ num, label, value }) => {
    const isBold = [3, 6, 8].includes(num);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.text(`${num}. ${label}`, margin, y);
    doc.text(formatCurrency(value), valueX, y, { align: "right" });
    if (isBold) {
      doc.setDrawColor(180);
      doc.line(margin, y + 1.5, pageWidth - margin, y + 1.5);
    }
    y += 7;
  });

  y += 10;

  // Certification section
  doc.setDrawColor(0);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("CERTIFICATE FOR PAYMENT", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  if (app.certified_amount != null) {
    doc.text(`Amount Certified: ${formatCurrency(app.certified_amount)}`, margin, y);
    y += 6;
    doc.text(`Certified By: ${app.certified_by || "—"}`, margin, y);
    y += 6;
    doc.text(
      `Date: ${app.certified_date ? new Date(app.certified_date).toLocaleDateString() : "—"}`,
      margin,
      y
    );
  } else {
    doc.text("Amount Certified: ___________________________", margin, y);
    y += 10;
    doc.text("Signature: ___________________________", margin, y);
    doc.text("Date: _______________", pageWidth / 2 + 20, y);
  }

  // Footer
  y += 15;
  doc.setFontSize(7);
  doc.setTextColor(128);
  doc.text(
    `Generated by RCG Work on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    y,
    { align: "center" }
  );

  const fileName = `G702_App${app.application_number}_${project.projectNumber || "project"}.pdf`;
  return { doc, fileName };
}

function buildG703Doc(
  app: PaymentApplication,
  appLines: PaymentApplicationLineWithSOV[],
  project: ProjectInfo
): { doc: jsPDF; fileName: string } {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  let y = margin;

  // Title
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("AIA DOCUMENT G703 — CONTINUATION SHEET", pageWidth / 2, y, { align: "center" });
  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(
    `Application No: ${app.application_number}  |  Project: ${project.projectNumber || ""} ${project.projectName}  |  Period To: ${new Date(app.period_to).toLocaleDateString()}`,
    pageWidth / 2,
    y,
    { align: "center" }
  );
  y += 8;

  // Table headers
  const cols = [
    { label: "A\nItem #", width: 14, align: "center" as const },
    { label: "B\nDescription of Work", width: 60, align: "left" as const },
    { label: "C\nScheduled Value", width: 28, align: "right" as const },
    { label: "D\nFrom Previous\nApplication", width: 28, align: "right" as const },
    { label: "E\nThis Period", width: 28, align: "right" as const },
    { label: "F\nMaterials\nStored", width: 25, align: "right" as const },
    { label: "G\nTotal Completed\n& Stored", width: 28, align: "right" as const },
    { label: "G%\n%", width: 14, align: "right" as const },
    { label: "H\nBalance To\nFinish", width: 28, align: "right" as const },
    { label: "I\nRetainage", width: 25, align: "right" as const },
  ];

  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y, pageWidth - margin * 2, 14, "F");

  doc.setFontSize(6.5);
  doc.setFont("helvetica", "bold");
  let x = margin;
  cols.forEach((col) => {
    const headerLines = col.label.split("\n");
    headerLines.forEach((line, i) => {
      const textX = col.align === "right" ? x + col.width - 1 : col.align === "center" ? x + col.width / 2 : x + 1;
      doc.text(line, textX, y + 4 + i * 3, { align: col.align === "left" ? "left" : col.align });
    });
    x += col.width;
  });
  y += 16;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  const rowHeight = 6;

  const renderRow = (values: string[], isBold: boolean, fill: boolean) => {
    if (y + rowHeight > pageHeight - 15) {
      doc.addPage();
      y = margin;
    }
    if (fill) {
      doc.setFillColor(245, 245, 245);
      doc.rect(margin, y - 1, pageWidth - margin * 2, rowHeight, "F");
    }
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    let rx = margin;
    values.forEach((val, i) => {
      const col = cols[i];
      const textX = col.align === "right" ? rx + col.width - 1 : col.align === "center" ? rx + col.width / 2 : rx + 1;
      doc.text(val, textX, y + 3, { align: col.align === "left" ? "left" : col.align });
      rx += col.width;
    });
    y += rowHeight;
  };

  appLines.forEach((line, idx) => {
    renderRow(
      [
        line.sov_line_item.item_number,
        line.sov_line_item.description.substring(0, 45),
        formatCurrency(line.scheduled_value),
        formatCurrency(line.previous_work),
        formatCurrency(line.current_work),
        formatCurrency(line.stored_materials),
        formatCurrency(line.total_completed),
        `${line.percent_complete.toFixed(1)}%`,
        formatCurrency(line.balance_to_finish),
        formatCurrency(line.retainage),
      ],
      false,
      idx % 2 === 1
    );
  });

  // Grand total
  const totals = appLines.reduce(
    (acc, l) => ({
      scheduled: acc.scheduled + l.scheduled_value,
      previous: acc.previous + l.previous_work,
      current: acc.current + l.current_work,
      stored: acc.stored + l.stored_materials,
      completed: acc.completed + l.total_completed,
      balance: acc.balance + l.balance_to_finish,
      retainage: acc.retainage + l.retainage,
    }),
    { scheduled: 0, previous: 0, current: 0, stored: 0, completed: 0, balance: 0, retainage: 0 }
  );

  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 2;

  const overallPct = totals.scheduled > 0 ? ((totals.completed / totals.scheduled) * 100).toFixed(1) : "0.0";
  renderRow(
    [
      "",
      "GRAND TOTAL",
      formatCurrency(totals.scheduled),
      formatCurrency(totals.previous),
      formatCurrency(totals.current),
      formatCurrency(totals.stored),
      formatCurrency(totals.completed),
      `${overallPct}%`,
      formatCurrency(totals.balance),
      formatCurrency(totals.retainage),
    ],
    true,
    false
  );

  // Footer
  doc.setFontSize(6);
  doc.setTextColor(128);
  doc.text(
    `Generated by RCG Work on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 8,
    { align: "center" }
  );

  const fileName = `G703_App${app.application_number}_${project.projectNumber || "project"}.pdf`;
  return { doc, fileName };
}

// ─────────────────────────────────────────────────────────────────────────────
// STORAGE — save PDF to Supabase Storage + project_documents
// Follows the exact pattern from reportStorageUtils.ts
// ─────────────────────────────────────────────────────────────────────────────

async function savePdfToStorage(
  pdfBlob: Blob,
  fileName: string,
  projectId: string,
  documentType: string,
  description: string
): Promise<PdfSaveResult> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const timestamp = Date.now();
  const sanitizedName = fileName.replace(/[^a-zA-Z0-9._-]/g, "_");
  const storagePath = `${projectId}/aia-billing/${timestamp}-${sanitizedName}`;

  // Upload to project-documents bucket (same as contracts and reports)
  const { error: uploadError } = await supabase.storage
    .from("project-documents")
    .upload(storagePath, pdfBlob, {
      contentType: "application/pdf",
      cacheControl: "3600",
      upsert: false,
    });
  if (uploadError) throw new Error(`Upload failed: ${uploadError.message}`);

  // Get public URL (same pattern as DocumentUpload.tsx)
  const { data: { publicUrl } } = supabase.storage
    .from("project-documents")
    .getPublicUrl(storagePath);

  // Insert into project_documents table (so it appears in Documents tab)
  const { error: dbError } = await supabase
    .from("project_documents")
    .insert({
      project_id: projectId,
      document_type: documentType,
      file_name: fileName,
      file_url: publicUrl,
      file_size: pdfBlob.size,
      mime_type: "application/pdf",
      uploaded_by: user.id,
      description,
    });
  if (dbError) throw new Error(`Failed to save document record: ${dbError.message}`);

  return { publicUrl, storagePath, fileName };
}

// ─────────────────────────────────────────────────────────────────────────────
// PUBLIC API — generate + save + download
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate G702 PDF, save to Supabase Storage, update payment_applications
 * record with PDF URLs, and trigger browser download.
 */
export async function generateAndSaveG702(
  app: PaymentApplication,
  project: ProjectInfo
): Promise<PdfSaveResult> {
  const { doc, fileName } = buildG702Doc(app, project);
  const pdfBlob = doc.output("blob");

  // Save to storage + project_documents
  const dateStr = format(new Date(), "MMM d, yyyy");
  const description = `AIA G702 — Application #${app.application_number} (${dateStr})`;
  const result = await savePdfToStorage(
    pdfBlob,
    fileName,
    project.projectId,
    "aia-g702",
    description
  );

  // Update payment_applications record with PDF reference
  const newVersion = (app.version || 0) + 1;
  await supabase
    .from("payment_applications")
    .update({
      g702_pdf_storage_path: result.storagePath,
      g702_pdf_url: result.publicUrl,
      version: newVersion,
    })
    .eq("id", app.id);

  // Trigger browser download
  doc.save(fileName);

  return result;
}

/**
 * Generate G703 PDF, save to Supabase Storage, update payment_applications
 * record with PDF URLs, and trigger browser download.
 */
export async function generateAndSaveG703(
  app: PaymentApplication,
  appLines: PaymentApplicationLineWithSOV[],
  project: ProjectInfo
): Promise<PdfSaveResult> {
  const { doc, fileName } = buildG703Doc(app, appLines, project);
  const pdfBlob = doc.output("blob");

  // Save to storage + project_documents
  const dateStr = format(new Date(), "MMM d, yyyy");
  const description = `AIA G703 — Application #${app.application_number} Continuation Sheet (${dateStr})`;
  const result = await savePdfToStorage(
    pdfBlob,
    fileName,
    project.projectId,
    "aia-g703",
    description
  );

  // Update payment_applications record with PDF reference
  await supabase
    .from("payment_applications")
    .update({
      g703_pdf_storage_path: result.storagePath,
      g703_pdf_url: result.publicUrl,
    })
    .eq("id", app.id);

  // Trigger browser download
  doc.save(fileName);

  return result;
}
