// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clsjdxwbsjbhjibvlqbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc2pkeHdic2piaGppYnZscWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjQ1OTUsImV4cCI6MjA3MzU0MDU5NX0.rN4HUHV1ZTSUHTDEsqmPDJcC5aIdVRWQjpf3RY3dQxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});