// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clsjdxwbsjbhjibvlqbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc2pkeHdic2piaGppYnZscWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjQ1OTUsImV4cCI6MjA3MzU0MDU5NX0.rN4HUHV1ZTSUHTDEsqmPDJcC5aIdVRWQjpf3RY3dQxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    // P0 (May 2026): autoRefreshToken disabled.
    // The auto-refresh path was firing under load (multiple realtime
    // subscriptions + rapid post-login API calls), hitting Supabase's
    // refresh-token rate limit (30/5min), 429-cascading, and
    // supabase-js's failure handling was clearing the session each
    // time. Result: users were briefly signed out mid-session, the
    // post-signin .from('profiles').single() queries 406'd because
    // the request fell back to the anon key, and AppLayout bounced
    // them back to /auth in a loop.
    //
    // With autoRefreshToken=false, the access token is used for its
    // full lifetime (1 hour by default) and then the session simply
    // ends. User re-logs-in once an hour. Acceptable trade-off vs.
    // not being able to log in at all.
    autoRefreshToken: false,
  }
});